listen_addr: 0.0.0.0:1234

users:
- name: plorio
  targets:
  - playit_prod
  - playit_dev
  clients:
  - jump_host_sea_1

clients:
- name: jump_host_sea_1
  api_key: 12314j2k1l3j21kl

targets:
- name: playit_prod
- name: playit_dev

paths:
  root: "/easy-sshca"
  tls_crt: "/easy-sshca/self-signed.crt"
  tls_key: "/easy-sshca/self-signed.key"

