//! gRPC message types generated from `proto/easysshca/v1/ca.proto` and the
//! operation catalogue shared by the server, the storage layer and the CLI.

use std::{fmt, str::FromStr};

tonic::include_proto!("easysshca.v1");

impl fmt::Debug for Command {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Command([redacted])")
    }
}

impl fmt::Debug for Reply {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Reply([redacted])")
    }
}

macro_rules! operations {
    ($($variant:ident),* $(,)?) => {
        /// Every RPC the certificate authority serves.
        ///
        /// The variant name is the wire name used in audit events, metrics,
        /// idempotency records and page tokens.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub enum Operation {
            $($variant),*
        }

        impl Operation {
            pub const ALL: &'static [Operation] = &[$(Operation::$variant),*];

            pub fn name(self) -> &'static str {
                match self {
                    $(Operation::$variant => stringify!($variant)),*
                }
            }
        }
    };
}

operations! {
    GetStatus,
    Unlock,
    CreateZone,
    ImportZone,
    ListZones,
    UpdateZone,
    RemoveZone,
    CreateUser,
    ListUsers,
    UpdateUser,
    RemoveUser,
    GrantZone,
    RevokeZone,
    ListUserZones,
    CreateAccessToken,
    ListAccessTokens,
    UpdateAccessToken,
    RemoveAccessToken,
    ClearTotp,
    RotateAdminKey,
    BeginTotpEnrollment,
    ConfirmTotpEnrollment,
    RotateToken,
    SignCertificate,
    GetPublicKey,
}

impl Operation {
    /// Operations that require an admin key rather than an access token.
    pub fn is_admin(self) -> bool {
        use Operation::*;
        matches!(
            self,
            CreateZone
                | ImportZone
                | ListZones
                | UpdateZone
                | RemoveZone
                | CreateUser
                | ListUsers
                | UpdateUser
                | RemoveUser
                | GrantZone
                | RevokeZone
                | ListUserZones
                | CreateAccessToken
                | ListAccessTokens
                | UpdateAccessToken
                | RemoveAccessToken
                | ClearTotp
                | RotateAdminKey
        )
    }

    /// Paginated read-only operations.
    pub fn is_list(self) -> bool {
        use Operation::*;
        matches!(
            self,
            ListZones | ListUsers | ListUserZones | ListAccessTokens
        )
    }

    /// Operations that do not authenticate with an API key.
    pub fn is_anonymous(self) -> bool {
        use Operation::*;
        matches!(self, GetStatus | Unlock | GetPublicKey)
    }

    /// Reads whose request UUID may be generated by the server when omitted.
    pub fn is_read(self) -> bool {
        use Operation::*;
        self.is_list() || matches!(self, GetStatus | GetPublicKey)
    }

    /// Operations that replace the caller's credential.
    pub fn is_rotation(self) -> bool {
        use Operation::*;
        matches!(self, RotateToken | RotateAdminKey)
    }
}

impl fmt::Display for Operation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

#[derive(Debug)]
pub struct UnknownOperation;

impl FromStr for Operation {
    type Err = UnknownOperation;

    fn from_str(name: &str) -> Result<Self, Self::Err> {
        Operation::ALL
            .iter()
            .copied()
            .find(|op| op.name() == name)
            .ok_or(UnknownOperation)
    }
}
